### ISSUE TITLE
About/Introduction page

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#116]
We need a short about/introduction page, especially for new visitors. The text is already written (English and German) and I've been talking to Paolo about a few illustrations of the game's scifi background story. For now, the question is how/where exactly to add  the text to the site (preferably in a place / in a way that will also work for a text with a few illustrations).

My proposal: When a new user visits veganaut.net, they see the about-text on a transparent white background, with the map and the map-specific buttons (register, products, search, filter) being faintly visible beneath. The veganaut-logo, the login-icon and the burger are visible at the top. Clicking the burger will first close the about-text (rolling it up like the burger-menu is rolled up when it is closed), shortly exposing the map and the map-specific buttons underneath, and then open the burger menu (rolling it down over the map just like it does now). Clicking on the veganaut-logo when the about-text is not visible will open the about-text again (rolling it down over the map just like the burger-menu does it now). Clicking on the veganaut-logo when the about-text is open (i.e. rolled down) will make it close (i.e. roll up).

So from a user experience perspective, the about text / the introduction page is "in" the veganaut-logo, which kind of makes sense. Also, I think it's good because on big screens this allows us to use the whole width of the screen instead of just the narrow section we now use for the location previews and such.

**Comment by toebu** [comment]
I propose the following:
- Replace the login-icon (left of the burger) with a help-icon and let that open the intro view
- This help-icon is of course also there when you are logged in and is available on every page
- The intro view overlays the whole page (except the header) like you suggested and is semi-transparent. It has a close button (x-icon) at the top right to close it. Pressing the help-icon again also closes the view.
- Opening the menu keeps the intro view open, but navigating to a different page through the menu closes the intro view
- Let's not do any animations (rolling up/down). Animations are a separate issue we can tackle once for all the elements of the page.

Why a help-icon instead of using the logo? The logo always links to the start page (or doesn't do anything) on almost every single page on the web. We can't break expectations like this.

**Comment by SebuLeugger** [comment]
This is how we'll do it: 

- move the map view from veganaut.net to veganaut.net/map
- create a new page at veganaut.net: this is the about/introduction-page featuring the intro text plus (as soon as they're done) some illustrations
- the about/intro page has the same header as all the pages: the logo, the login button, the burger
- the logo is always a link to the about/intro page
- we'll somehow integrate a view of the map into the about/intro page. However, that will be mainly a design feature; users won't be able to interact with the map when they're on the about/intro page, or only in a very limited way like e.g. with the small map section that is visible in the location details view, but maybe not even that. The main flow we want to encourage is: read intro if you're interested, and then immediately click on something (a link, a map preview...) that takes you to the veganaut.net/map view.
