### ISSUE TITLE
Teams page: player ranking: choose criterion

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#131]
Currently, the player ranking ranks players only according to the number of missions they've completed. We should instead let users choose which ranking they want to see: total missions? pioneer score? diplomat score? etc. 

Currently, there are only 4 attributes plus the total missions, which makes 5 rankings. We could just have 5 buttons for each of these rankings. Or we could have a drop-down to choose the ranking criterion. Anything is fine. 

Maybe we even want to get rid of the total missions ranking. Pro: missions may become even more fuzzy in the future, such that counting them makes even less sense than it does now. (cf. #110 and especially #129) Con: @filodoofus will be sad because he loses his lead in that ranking. And thus Pro 2: if we get rid of that ranking now he'll be less sad than if we get rid of the ranking even later, after even more investment :)

Anyway, ff we do get rid of the total missions ranking we might as well get rid of the total missions stat in the players' profiles.

**Comment by SebuLeugger** [comment]
@toebu since you are working on this now, maybe read it and reference your commits here.

**Comment by toebu** [comment]
This is now done the following way:
The first ranking is by owned locations. After that there is still the ranking by missions.
I would sooner or later replace it with rankings based on the player attributes (whatever those will be). The mission count indeed doesn't really say that much anymore. Especially because now every time you rate something, it is counted as a separate mission.
Anyway, I would close this and we'll re-visit it when we'll improve the player attributes.
