### ISSUE TITLE
Add recent missions to player profile

### ISSUE THREAD

**Issue by filodoofus** [veganaut/veganaut#150]
Maybe we could add a list of, say 5, recently completed missions and/or recently visited locations (i.e. locations where any mission was completed) to the player profile.

In our discussion, you were reluctant to put too many medals/achievements to the profile, so maybe this is against some design/UI decision you made.

**Comment by SebuLeugger** [comment]
I think it's a good idea to limit the length of such a list to 5 or maybe even fewer items. Maybe we could even incorporate the limitation into the game & the background story: when veganauts want news they have to connect to their motherships or use otherwise limited bandwidths, so they can only get a limited amount of news per day or so. Maybe you'd have to "pay" to see the list of recent activities of some player, an maybe you have to "pay" more if she's from another team than you.

The main reason why I'm in favor of limiting the number of items is that I hate the fact that on Facebook and twitter etc. they encourage you waste time by providing an endless stream of news, which add no value to your life. We only need a little bit of news to give players the experience of getting news and of being part of something that moves and changes. I don't want them to waste time on veganaut, even if it would mean they stay on the site longer and we could show them more advertisements. I hate that business model.

**Comment by SebuLeugger** [comment]
Because of privacy reasons, we don't want this.
