### ISSUE TITLE
Improve start page with a more obvious call to action

### ISSUE THREAD

**Issue by toebu** [veganaut/veganaut#186]
User testing showed that the current start page does not make it easy to understand what the page is about and to quickly get to a list or a map of locations around where you are.

**Comment by SebuLeugger** [comment]
Maybe we should somehow define two kinds of areas - those where we have lots of locations (e.g. Switzerland) and those we hardly have any or have none at all (e.g. the US) - and then have two different starting pages / calls to action based on where the person looking at the page is located. So if they're in the US we'd tell them basically: look, in the US you have to be a pioneer and enter locations, because hardly any veganauts have gone there, and the call to action wouldn't be "find vegan locations nearby" because that is only going to frustrate users. In the areas like Switzerland where we have a lot of information, the call to action can be "find locations"

**Comment by toebu** [comment]
@SebuLeugger: I agree it's a good idea to have a different start page for countries where we have few locations, but this is secondary since these are also the countries where we have few visitors. So I would propose to make a separate issue for that.

I made a bunch of design proposals for the new start page (thanks to @alesiom for your awesome inputs!)
![veganauthomepage01](https://cloud.githubusercontent.com/assets/1837568/15653950/97813978-2690-11e6-8f62-71d58fcb4a97.png)
![veganauthomepage02](https://cloud.githubusercontent.com/assets/1837568/15653951/9785e95a-2690-11e6-88a0-bf053feb47ae.png)
![veganauthomepage03](https://cloud.githubusercontent.com/assets/1837568/15653952/978a6aa2-2690-11e6-878d-b9d3624927c5.png)
![veganauthomepage04](https://cloud.githubusercontent.com/assets/1837568/15653953/978e99ec-2690-11e6-8b1f-5a4f66bb2c52.png)
![veganauthomepage05](https://cloud.githubusercontent.com/assets/1837568/15653954/97946f5c-2690-11e6-9d3d-999680ebf54f.png)
![veganauthomepage06](https://cloud.githubusercontent.com/assets/1837568/15653956/97a0ba50-2690-11e6-9c4f-832219e6474e.png)
![veganauthomepage07](https://cloud.githubusercontent.com/assets/1837568/15653955/979e16e2-2690-11e6-8523-488fde0978be.png)
![veganauthomepage08](https://cloud.githubusercontent.com/assets/1837568/15653957/97a28c2c-2690-11e6-9fd6-3e73f7f65917.png)
![veganauthomepage09](https://cloud.githubusercontent.com/assets/1837568/15653958/97a6e240-2690-11e6-9dd9-fbc930a46e02.png)
![veganauthomepage10](https://cloud.githubusercontent.com/assets/1837568/15653959/97aed9fa-2690-11e6-9ef2-b1c817a5b814.png)

**Comment by filodoofus** [comment]
I would go with a version with a picture (not because I made it). It looks friendly and it's clear what the app is for. The non-picture version look rather abstract and don't pull me in in the same way. From the examples you made, the one with the veganaut logo front and center (https://cloud.githubusercontent.com/assets/1837568/15653956/97a0ba50-2690-11e6-9c4f-832219e6474e.png) looks best to me.

**Comment by SebuLeugger** [comment]
Great designs. I agree with @filodoofus that the one with the photos are most appealing and that the one with the logo front and center is best.

A question: what happens if I press "show map" when an area as huge as "Switzerland" is selected? Does it load all the locations in that map section? Or could we maybe show only the best locations (i.e. have an offerQuality filter set to 5-twig locations by default, or even like so: show only the 20 locations that would be displayed of the first page in the list view, and have a "show more locations" button somewhere on the map (which loads the next 20 locations that would show up on the list view)? Or do you already have another solution for this?

**Comment by toebu** [comment]
This is live (not showing top locations yet, but that will be moved to a separate ticket).
