### ISSUE TITLE
Find a good solution for loads of locations on the map

### ISSUE THREAD

**Issue by toebu** [veganaut/veganaut#188]
When zooming out to see more than a city, there are too many markers on the map. We need to find a solution that gives the user the necessary information and works from a performance points of view.

**Comment by toebu** [comment]
Suggestion:
![veganautmap04](https://cloud.githubusercontent.com/assets/1837568/15713180/a066ed54-2815-11e6-9525-2a2729a1edbb.png)

There are two things going on here:
- Show some high-quality locations that don't overlap (too much) as normal location dots.
- Show clustered information on where there are more locations to be found if you zoom in.

This will take a while to implement, but I found all the basic ingredients and performance both on the server side and the client side should be much better than it is now.

**Comment by SebuLeugger** [comment]
As discussed, I like the concept, and now that I see it I believe it will work. I also see my suspicion confirmed that the visual representation is confusing if we use two different colours for the cluster dots and the location dots. I don't see the location dots as highlights of what the cluster dots represent, but as something unrelated, and I don't expect to see more of the white dots when I zoom into the greenblue dots. Can you make an example where the white dots are bluegreen (and the symbol and the border is white instead of black)? - And maybe add a white border to the cluster dots as well? That looked nice when we still had five colours, remember? Like bubbles.

**Comment by SebuLeugger** [comment]
Maybe in addition it would be useful to have a cluster-icon inside the cluster dots? E.g. three circles within a circle, a bit like so: https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/DescartesCircles.svg/220px-DescartesCircles.svg.png ? - Just brainstorming.

**Comment by toebu** [comment]
Here are a bunch more with different styles. I agree that the same colour is better. Having an icon in the clusters doesn't really work because it's just too tiny. I think it's also good to have a clear difference so the user does not get confused what is clickable and what not.

thick - thick:
![mapclustering01](https://cloud.githubusercontent.com/assets/1837568/15749898/80bfd752-28e4-11e6-92f8-cabf5efa521d.png)
thin - thick:
![mapclustering02](https://cloud.githubusercontent.com/assets/1837568/15749899/80c137aa-28e4-11e6-9b15-b70b8670faa5.png)

thick - thin:
![mapclustering03](https://cloud.githubusercontent.com/assets/1837568/15749903/80cd371c-28e4-11e6-95f6-56d75564f140.png)
thin - thin:
![mapclustering04](https://cloud.githubusercontent.com/assets/1837568/15749901/80c39cfc-28e4-11e6-85e3-9c5a5bf41f81.png)

thick - none
![mapclustering05](https://cloud.githubusercontent.com/assets/1837568/15749900/80c25162-28e4-11e6-85bb-32b4a819309c.png)
thin - none
![mapclustering06](https://cloud.githubusercontent.com/assets/1837568/15749902/80c44648-28e4-11e6-82b9-7c30103248e4.png)

I like thick-thin the most, then they really look like smaller versions of the clickable marker.

**Comment by filodoofus** [comment]
Yes the colours are much better like this. The thick-thick version looks best to me because it has a consistent style and represents the differences in quality of the various locations the best.

**Comment by toebu** [comment]
Actually, the size (and opacity) of the circles without the icons is determined by how many locations they represent, not the quality of the circles. There are currently 4 sizes of the cluster-dots: the smallest represents just 1 place, the next 3 are for more and more locations (don't know the exact numbers).

So we might have to be careful that the quality and the number of locations is not confused. We make it hard because we use the same indicator (size of circle and opacity) for both dimensions. The difference being: no icons, overall smaller, not clickable.

**Comment by SebuLeugger** [comment]
I showed the dots on the map above to someone who didn't know what they are supposed to show and they misunderstood the idea, thinking that the small dots without icons are just small versions of the large dots with icons. They suggested we add something like a magnifying glass or some other design solution to make it clear that the small dots are clusters of what the large dots represent (it is a bit counter-intuitive that small dots represent collections of large dots :) 

So while two colours suggested that the two kinds of dots have no relation whatsoever, the same colour suggests that they are the same. I made an ameteurish mockup of another possible solution: 
![cluster-highlight](https://cloud.githubusercontent.com/assets/6586945/15773115/7af0168e-2975-11e6-82dc-0cabafce1fc5.png)

What do you think?

**Comment by filodoofus** [comment]
Maybe it's not so important whether the small dots correctly represent what people think it represents but that people interact with the dots the way we want them to interact with them. It seems to me that a common response to the small dots would be to zoom in. My guess is that once we add that dynamic element to it, people will quickly realise what the dots represent anyway.

**Comment by alesiom** [comment]
I would concur with filo. I don't think it matters that much. On the contrary it is something that is part of the discovery phase. What needs to be well made is that when the user zooms in, the small green dots bubble into other dots - or if near enough - the location directly. Same for zoom out. 

The question that remains is : 
 "Show some high-quality locations that don't overlap (too much) as normal location dots." --> is this of interest when you really zoom out? Or is it rather distracting? I could imagine that people would be interest of such high-quality highlights when zoomed in about 50km. (basically a city and its surrounding). 

PS I really like the overall solution, much better than the current one which nearly freezes my phone.

**Comment by SebuLeugger** [comment]
Yes, the dynammic/interaction dimension might solve this problem. 

About this: "Show some high-quality locations that don't overlap (too much) as normal location dots." - I think we need this also on the country/continent level because of this likely flow: start page: user selects "find vegan offers in [Germany] - show on map" -> user is taken to a map of Germany. If the user now can't click on something that is obviously a vegan offer they might get frustrated. Also, the cluster dots are not clickable, so without the highlighted locations  users would get a completely non-interactive map on the country level and above. - But you're right that on this level they maybe don't care about individual locations. So maybe the point of the highlighted locations is rather to get users to explore the map more, and to explain to them what kind of information they will find if they zoom in more. - Does it make sense to do that in this way, or is there a better solution?

**Comment by SebuLeugger** [comment]
Btw, now that we added borders to the cluster dots I think it might again work if all the dots were white (and the borders black) instead of bluegreen. Can you do e.g. a thin-thin mockup with white dots and black borders, @toebu?

**Comment by toebu** [comment]
Thanks for all the feedback! Animations would definitely be great, I'll see when I'll implement it if something is doable in a decent time.

@SebuLeugger: could do a mockup with white dots, the problem was though that the map style we are using has small white dots with black borders to denote cities at some zoom levels. So I think that would be confusing... But I'll try it on Monday.

In any case, we all seem to agree that this is the way to go, so I'll start implementing. Changing colours or borders will be easy once we have a working version. Then we can also interact with it and see how it feels like to zoom in and out.

**Comment by toebu** [comment]
I now finished the first working version (in crappy code) and put it on https://test.veganaut.net/map. 

Note that certain other features except the map (map on start page, product list) are probably broken at the moment.

Please test and give feedback. Open questions:
- Colours/Styles
- At what zoom level should we switch to always showing all locations?

**Comment by SebuLeugger** [comment]
Here's my feedback:

- For me, white/white with black borders (the way you did it) works; I don't confuse the smaller map markers denoting villages and cities with the cluster dots. Then again, maybe that's because I already know what to look for. Maybe if the cluster dots were a bit bigger still it would be more clear? Or if we used think borders throughout? 

- performance-wise it's great the way you did it, it even works on my crappy phone. 

- I'm not sure whether new users get what the cluster and the highlighted location dots stand for by zooming in and out. I understand it, and I feel like others should, too. But I'm obviously biased. 

- I think there shouldn't be any clusters any more at about zoom level 13 or 14 upwards. Or is this too soon?

- I feel like shopping locations get too much of the spotlight as highlighted locations. Do others feel the same way? As a user, I think by default I'd rather see more restaurants, or even only restaurants, at least at zoom levels between 0 and, say, 10. What do others think? And how could we solve this?

- In this context, I was wondering how the clusters and especially the highlighted locations are supposed to interact with filters. Currently, if I filter out e.g. shopping locations, they just disappear, without being replaced by whatever is the best restaurant location for that cluster. I think they should be replaced in this way. So the rule should be (more or less): re-load the highlighted locations every time the filter settings change, so that the best location passing all the filters is shown for the cluster that had a highlighted location before.

**Comment by SebuLeugger** [comment]
Some time ago we thought about whether we should still show the locations that don't pass the filter (cf. https://github.com/veganaut/veganaut/issues/136#issuecomment-89769711) Maybe this is the time to revive this discussion. Instead of showing all locations with big clickable dots at zoom level 13 upwards we could just by default filter out all the locations with 3 twigs or lower at this zoom level and show them like the 1-location cluster dots (i.e. like the smallest cluster dots). Maybe at zoom level 15 or 16 upwards we could show the 3-twigs locations also, i.e. only filter out the locations with 2 twigs or lower. (This issue should probably be completed if we do this: https://github.com/veganaut/veganaut/issues/123)

**Comment by toebu** [comment]
This is live!
