### ISSUE TITLE
Fix styling of menu in firefox

### ISSUE THREAD

**Issue by toebu** [veganaut/veganaut#236]
![screenshot_20171213_141520](https://user-images.githubusercontent.com/1837568/33940648-15198130-e010-11e7-8b33-5734726f5192.png)

**Comment by davidsandoz** [comment]
Quickly investigated this. It is apparently due to Firefox ignoring percentage values for margin on flexbox elements.
In [this SO question](https://stackoverflow.com/questions/33502702/flex-elements-ignore-percent-padding-in-firefox), they recommend not using percentages in that situation.

@raydirty Can you fix that please?
