### ISSUE TITLE
Public Profiles

### ISSUE THREAD

**Issue by SebuLeugger** [veganaut/veganaut#86]
Players should have public profiles (which can be accessed e.g. by clicking on their names in the "teams" view), or rather: part of the players' profile should be publicly visible. What elements should be publicly visible:

- name
- number of missions completed
- maybe: list of missions completed 
- maybe: list/number of locations where this player completed at least one mission at some time (whether or not they still belong to her team)
- maybe: list/number of locations added by this player (whether or not they still belong to her team)
- maybe: list/number of locations conquered by this player and not lost to another team since (where she actually completed the decisive mission which turned the location from another team to her team, or where she added the location)
- maybe: list/number of locations successfully defended/reinforced by this player (i.e. locations belonging to her team in which she completed at least one mission since the location belonged to her team)
- maybe: list/number of locations attacked by this player (i.e. locations belonging to another team where she completed at least one mission since they belonged to that team)
- maybe: total number of points made with missions (never goes down) / number of points still "owned" at locations (goes down if you do nothing)

Probably it makes sense to just show the numbers of all of these things, and to only show the list when people click on these numbers. 

Of course, these stats also show in every players private "profile" view. We could also give them badges that work like high water marks: if a player reaches e.g. 100 locations conquered at some point, she gets a "100" badge that she can keep forever, even if these 100 locations are subsequently conquered by other teams and her currently conquered locations go down to e.g. 5. So in addition to the current numbers, the public (and private) profile should contain:

- badges: high water marks of the various numbers listed above: in roughly logarithmic steps 1, 10, 100, 500, 1000 etc. (i.e. you don't get a 106-badge if your max number was 106, you just get a 100 badge and have to work until 500 to get the next higher badge or so.)
- maybe: badges for highest rate of change in the various numbers listed above (e.g. highest number of new locations added in a single week. or highest number of missions completed in a single day. Again in logarithmic steps: i.e. 1, 10, 100,...)

When clicking on a badge you're shown the list of whatever the badge was awarded for (e.g. the locations then conquered by this player and then owned by her team)

**Comment by toebu** [comment]
To make these stats a bit less dry, I would suggest to sum them up in kind of characteristic that describe this player. Here is a first suggestion of characteristics and which missions and actions would increase that characteristic:
- **Prospector**: addLocation, whatOptions, first visitBonus/hasOptions/wantVegan/whatOptions/rateOptions/offerQuality/effortValue at location
- **Talker**: hasOptions, wantVegan, giveFeedback
- **Evaluator**: rateOptions, offerQuality, effortValue
- **Sampler**: visitBonus, buyOptions
- **Conqueror**: location taken over from other team, location of other team attacked
- **Defender**: missions completed at location of own team
The different missions or events could influence the characteristics by different amounts. Adding a new location would for example increase the prospector stat by more than adding a new option at a location.

These are all stats that only go up. Additionally one could add a few fluctuating stats that represent more the current state, as suggested by you:
- list/number of locations conquered by this player and not lost to another team since (or more difficult to calculate: number of locations that still belong to the player's team where the player was involved in conquering or defending)
- number of points still "owned" at locations (goes down if you do nothing)

I would also as soon as possible introduce more "social" stats. E.g. team work that goes up if you complete missions at a location together with a team mate.

If you like these characteristics, I would come up with a formula that we could then implement.

**Comment by toebu** [comment]
Before moving any further with the implementation we have to clarify what the goal is.

**Comment by filodoofus** [comment]
One option would be to have the profile (with whatever attributes are decided on) be an incentive to do more stuff. In order to have this function, you would need to be able to compare yourself easily with others. So, there would be some indication of how good you are overall.

Two examples: In Strava, when you join a challenge, you immediately are asigned a rank within all the people doing the challenge. You want to move up in the ranks, you want to be better. So you do more stuff. In Starcraft, you are placed into divisions. You get a rank, you want to move up, you want to get points. You want to become number 1. So you play more.

How could this work in Veganaut? Let's say we have the options that toebu suggested. You could compare yourself in various characteristics with others. I might be a lousy Prospector, but I'm an amazing Defender. This way, there is an easy way to compare yourself with others (apart from "number of missions completed"). We could have different standings for the different characteristics (sort by Prospector, sort by Defender, etc.).

If we have the statistics mean something in the game, as a means of comparison with other players, it would be interesting to all players and not just quantifier-guys like me.

**Comment by toebu** [comment]
We'll do it more or less as describe by me above. The names will be slightly different:
* Pioneer
* Socialiser
* Evaluator
* Gourmet
* Conqueror
* Defender

And yes @filodoofus, having different high scores for these characteristics would be the goal!

**Comment by toebu** [comment]
Created a bunch of new issues that should cover our first version of the player profiles
